export const endPoints = {
    saveorUpdateProducts: 'createProducts',
    saveorUpdateVendor: 'vendor',
    updateVendor : 'updateVendor',
    deleteVendor : 'deleteVendor',
    saveorUpdateContact: 'contact',
    getAllProducts: 'products',
    getAllVendor: 'vendor',
    getAllVendorUnPaid: 'vendorUnPaid',
    UpdateSingleProduct: 'updateproducts',
    Vendorlogin : 'vendorlogin',
    DeleteProduct : 'deleteproduct',
    saveCheckout : 'checkout',
    getAllCategories : 'category',
    getProductsByVendorId : 'products/vendor/',
    saveOrUpdateUser :'users',
    addProductsToCart:"cart",
    getProductsByCategory:"products/category/",
    createCheckout:"create-checkout-session",
    getCartbyId:"cart/",
    searchProductsByName:"products/",
    loginWithRoles:"login",
    getAllUsers:"users",
    updateUser:"updateUser",
    deleteUser:"deleteUser",
    updateVendorStatus:"update-vendor-status",
    paymentStatus : '/api/stripe/checkout-session/',
    deleteCartProducts : 'deleteCartProducts',
    soldproducts: 'soldproducts',
    productsById: 'productsById/',
    getSoldProductsByVendorId: 'getSoldProductsByVendorId/',
};